default: &default
  adapter: postgresql
  pool: 5
  timeout: 60000
  username: blog
  password: dbpass

development:
  <<: *default
  database: dev_blog

test:
  <<: *default
  database: test_blog

production:
  <<: *default
